### ISSUE TITLE
Retrieve only whitelisted attributes after validation

### ISSUE THREAD

**Issue by luislavena** [hanami/validations#24]
#21 introduced the ability to retrieve coerced attributes (`.attributes` or `.to_h`) after validation, however, it also carried over extra attributes that weren't validated or coerced.

Example:

``` ruby
class NewUser
  include Lotus::Validations

  attribute :name, type: String,  presence: true
  attribute :age,  type: Integer, presence: true
end

luis = NewUser.new(name: "Luis", age: "34", garbage: "foo")
luis.valid? # => true

luis.attributes # => {:name=>"Luis", :age=>34, :garbage=>"foo"}

# Expected:

luis.attributes # => {:name=>"Luis", :age=>34}
```

Having `attributes` return only the whitelisted and coerced values avoids the potential issue of sending parameters down to other objects that might have undesired effects.

While usage of `.attributes.slice` is possible, it leaks details about which fields are desired to the invoker.

Cheers

**Comment by akeuk** [comment]
It's not working on v0.6.0.

From @luislavena 

```ruby
luis = NewUser.new(name: "Luis", age: "34", garbage: "foo")
luis.attributes # => undefined method `attributes for ...

result = luis.validate
result.success? # => true
result.output # => {:name=>"Luis", :age=>34, :garbage=>"foo"}

# Expected:
result.output # => {:name=>"Luis", :age=>34}
```

What should I do for retrieve only whitelisted attributes.

Thanks.
