### ISSUE TITLE
Validations from Initializer

### ISSUE THREAD

**Issue by folkengine** [hanami/validations#109]
I recently tried updating my gem to 0.6.0 and noticed that I started receiving  "undefined method `validates'". I've had no success trying to update my Class to validate inside a constructor with a validations block as documented in the README. Is this functionality no longer supported?

Here's the code that works fine with version 0.5.0. 

```ruby
require 'hanami/validations'
class Name
  include Hanami::Validations
  MAX_NAME_LENGTH = 64
  attr_reader :name
  validates :name, type: String, size: 1..MAX_NAME_LENGTH, presence: true, format: /\A[\-_a-zA-Z1234567890]+\z/

  def initialize(name)
    @name = name.to_s
    raise "Invalid Name: #{name}" unless valid?
  end
end

n = Name.new('Goodname')
m = Name.new('Invalidname%%%%%%')

**Comment by cllns** [comment]
@folkengine There's a whole new syntax for validations introduced in `0.6.0`. It's more flexible and faster, but it does require changing your old validations, as the old syntax is no longer supported. 

Take a look at the current README for notes on this new syntax. The `validations` block goes *outside* of the constructor, just in the class definition (not inside any method definition).

You'll need to switch your class to something like:

```
class Name
  include Hanami::Validations

  attr_reader :name
  MAX_NAME_LENGTH = 64

  validations do
    required(:name) { str? & size?(1..MAX_NAME_LENGTH) & filled? & format?(/\A[\-_a-zA-Z1234567890]+\z/) }
  end

  def initialize(name)
    @name = name.to_s # Not sure if this `.to_s` is necessary
    raise "Invalid Name: #{name}" unless valid?
  end
end
```

Let me know if you have any trouble or questions!

**Comment by cllns** [comment]
I wrote up a quick class but I tried it out and it didn't work, so I edited it out of my last response.

This should work:
```
require 'hanami/validations'

class Name
  include Hanami::Validations
  MAX_NAME_LENGTH = 64
  attr_reader :name

  validations do
    required(:name) { str? & size?(1..MAX_NAME_LENGTH) & filled? & format?(/\A[\-_a-zA-Z1234567890]+\z/) }
  end
end

n = Name.new(name: 'Goodname')
n.validate.success? # => true
m = Name.new(name: 'Invalidname%%%%%%')
n.validate.success? # => false
```

The trouble is that when you include `Hanami::Validations`, it expects the initializer to take a hash of attributes.

This is a different approach than what you had, where you would throw an error instead of creating an invalid object. Here, we let the object be created, but when we call `validate` on it, it shows us what errors came up (for example, `n.validate.errors`). This is more flexible, since it enables us to have several specific error messages rather than just one.

We suggest using validations when the data comes in (as parameters for web apps, `Hanami::Controller::Action` if you're using `hanami-controller`), rather than putting them on the data itself.

**Comment by solnic** [comment]
Shorter version:

``` ruby
required(:name).value(:str?, size?: 1..MAX_NAME_LENGTH, format?: /\A[\-_a-zA-Z1234567890]+\z/)
```

**Comment by folkengine** [comment]
Guys,

Thanks for the quick response. I think I've figured out how to throw the exception from the constructor:

```ruby
require 'hanami/validations'
class Name

  attr_reader :name

  def initialize(name)
    @name = name.to_s

    n = NameValidator.new(name: name)
    raise "Invalid Name: #{name}" unless n.validate.success?
  end

  class NameValidator
    include Hanami::Validations
    MAX_NAME_LENGTH = 64

    validations do
      required(:name) { str? & size?(1..MAX_NAME_LENGTH) & filled? & format?(/\A[\-_a-zA-Z1234567890]+\z/) }
    end
  end
end

n = Name.new('Goodname')
puts "I'm good"
begin
  m = Name.new('Invalidname%%%%%%')
  puts "I can't explain this."
rescue
  puts "I had a booboo"
end
```

**Comment by cllns** [comment]
@folkengine Glad you figured it out. If you're all set, please close this issue :)

**Comment by cllns** [comment]
Woo hoo! If you need any more help, feel free to ask in our [Gitter chat](gitter.im/hanami/chat) :)

**Comment by solnic** [comment]
@folkengine just curious, what's the reason for raising in the constructor? It seems like you want strict typing, not validation.

**Comment by folkengine** [comment]
@solnic I like having my domain objects policing themselves as to what's valid. I like having my APIs do the work rather than forcing the caller into making another step. It feels cleaner to me to validate through the constructor rather than having an extra step to tell me something that I should already know. 

Strict typing wouldn't give me anything over what Ruby has. A String can still be empty and have any length and have any Unicode character. 

If this were a web application instead of an API I could see the need for a separate validate stage.
